### ISSUE TITLE
"_gvr_set_default_viewer_profile" undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by irgipaulius** [mobfishgmbh/Cardboard-VR-Unity-SDK#75] opened 2020-10-04 21:49 UTC
Hi.
So as you may know, iOS 14 fucked all GVR apps. yay.
I refuse using Cardboard XR because it does not provide all the functionality that my old GVR implementation had, so I found this repo and heard it supports Metal. I hope this will work on iOS 14 devices.

So I finished refactoring my app in a record-breaking 14 hours, and now when I archive xCode project, I'm faced with this:
```
Undefined symbols for architecture arm64:
  "_gvr_set_default_viewer_profile", referenced from:
      _GvrCardboardHelpers_SetViewerProfile_mA5AA4D3CE2B1069347C2A665EB51553D57E48F92 in Assembly-CSharp.o
      _GvrCardboardHelpers_gvr_set_default_viewer_profile_m0E3A23C0F7143C8574B26F27678AA4C024CF9C61 in Assembly-CSharp.o
     (maybe you meant: _GvrCardboardHelpers_gvr_set_default_viewer_profile_m0E3A23C0F7143C8574B26F27678AA4C024CF9C61)
  "_gvr_reset_tracking", referenced from:
      _GvrCardboardHelpers_Recenter_mFB068941B2B52795CAC3C30135BF80943DA8A0CF in Assembly-CSharp.o
      _GvrCardboardHelpers_gvr_reset_tracking_m820F2B0EE2207BCC19D8B649E17938EEC71FF099 in Assembly-CSharp.o
     (maybe you meant: _GvrCardboardHelpers_gvr_reset_tracking_m820F2B0EE2207BCC19D8B649E17938EEC71FF099)
  "_gvr_get_time_point_now", referenced from:
      _AndroidNativeKeyboardProvider_gvr_get_time_point_now_m375CFCE5625923A69155009C7A04BEBDE4B0D052 in Assembly-CSharp.o
      _AndroidNativeKeyboardProvider_UpdateData_mC14F1945CF74233DFEC04522D9FF0E9A949A36A1 in Assembly-CSharp.o
     (maybe you meant: _AndroidNativeKeyboardProvider_gvr_get_time_point_now_m375CFCE5625923A69155009C7A04BEBDE4B0D052)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried all solutions listed [here](https://stackoverflow.com/questions/55594849/xcode-keeps-giving-symbols-not-found-for-architecture-arm64) and elsewhere, except for a few:
- I cannot set "Virtual Reality Supported" and have "Cardboard" added in player settings, because the documentation of this wiki explicitly advises against it. Also I do not see those buttons - maybe that's a Unity 2020 thing?
- my Unity `2020.1 7f1` does not generate `.xcodeproj` file when it builds - maybe that's a Unity 2020 thing?

Any help or hint would be helpful and appreciated. Seriously, anything. Thanks

**Comment by cdytoby** [comment] 2020-10-09 08:31
Hello, sorry for the late response, I don't have a device with iOS 14 installed so I cannot test on this system, however, I tested Unity 2020.1.7 with this project, exported to xcode project on MacOS Catalina, and open with newest xcode I can get, deployed to an iOS 12 device, and it works, with a change that I need to add to the documentation.

Now to the issue you mentioned:

- The error log you posted, seems like you're using the old legacy cardboard, and these files or configuration are not deleted from your project. All old cardboard files should be deleted before import this cardboard package. GvrCardboardHelpers and AndroidNativeKeyboardProvider class don't exist in this new package.
  - If it doesn't help, you might want to test if delete your project settings helped. Because the related settings could be still in the setting file.
- Virtual Reality Supported should disappear in new Unity versions, because Unity stopped supporting the legacy XR support and start pushing the new XR Management forward. That's why you don't see these buttons. I'll check and improve the wiki on this point.
- xcodeproj is the weird one, I tested with Unity 2020.1.7 and it generates xcodeproj. Make sure you export your xcode project to an empty folder. And maybe there are some settings which prevent it generates? Is there any errors when export to XCode Project?

**Comment by irgipaulius** [comment] 2020-10-09 09:24
Thanks for the answer.
- I am using both libraries. mobfish for VR stuff, and gvr for GvrCardboardReticle as well as GvrEventSystem to interact with buttons. Refactoring this part would be a huge timesink for me, especially the EventTrigger system my project is built on...
  - you mentioned deleting project settings... well I created a fresh new project and added both libraries, established a basic scene, and upon xCode build - same errors. I've setup project settings to somewhat minimum requirements for the Apple Store.
    - Then I tried removing most of the internal scripts from the legacy GVR, but I was unsuccessful. Simply deleting "Plugins" folder from it just introduced more Unity build errors which I couldn't resolve.

It's been some time since my post, and it became clear that there is no "quick fix" solution, sadly. I will have to refactor everything ground-up using a more modern XR system...

I think we can close this issue, since there isn't really a simple solution to my complicated problem.

Personal note: This is eye-watering. I really liked working on mobfish cardboard. And I do not want to spend so much time on my massive 3 year old app which I built with horrific programming practices. The app still generates nice income, so it's going to be worth it,. Damn Apple, Y U bother me

**Comment by cdytoby** [comment] 2020-10-09 09:45
About the issue, as long as the legacy google cardboard package is included, this issue will happen, and I don't think they're related to this current cardboard package. 

And I feel your pain, large refactor requirement also happens to many other people including me. But this is a really common among programming world. Google and Apple rapidly changing their programs and SDKs, even Unity changes its things from time to time. The problem is inevitable in my opinion. My solution currently is never interact with plugin directly, always build a "layer" between project and plugin, so that when plugin is changed, the project doesn't have to change too much, and the "layer" can be adjusted for a new or another plugin. But even so, some major refactor is still requried.

I hope you get this over with soon, and wish you a success on whatever you're building.

I updated the document, and I'll close this issue. If you need help with this SDK you can create a new issue.

**Closed as completed by cdytoby** 2020-10-09 09:45 UTC
Labels: documentation, question

**Comment by hawkwood** [comment] 2020-10-09 18:57
I see this is closed, but I wanted to throw out an idea.  If memory serves, the GvrCardboardReticle and GvrEventSystem are Unity scripts and independent from the native portions of the Cardboard SDK. With little script work, you should be able keep those and still remove the native portions.
